title: 'Tomás Cornelles'
default_lang: es
author:
  name: 'Tomás Cornelles'
  email: tomascornelles@gmail.com
taxonomies:
  - tag
  - type
  - tech
  - client
  - year
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
