enabled: true
blog_thumbnail_width: 600
blog_thumbnail_height: 450
favicon:
  user/themes/mache/images/icono.png:
    name: icono.png
    type: image/png
    size: 1271
    path: user/themes/mache/images/icono.png
logo:
  user/themes/mache/images/principal.svg:
    name: principal.svg
    type: image/svg+xml
    size: 15666
    path: user/themes/mache/images/principal.svg
