enabled: true
color: red
left_footer: ''
blog_thumbnail_width: '600'
blog_thumbnail_height: '450'
favicon:
  user/themes/tc2018/images/icono.png:
    name: icono.png
    type: image/png
    size: 6224
    path: user/themes/tc2018/images/icono.png
